# Generated by Django 5.0.2 on 2024-02-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
